name: Deploy to Google Cloud Run

on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Google Cloud SDK
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      - name: Build and push Docker image
        run: |
          gloud auth configure-docker
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/project-management-app:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/project-management-app:${{ github.sha }}
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy project-management-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/project-management-app:${{ github.sha }} \
            --platform managed \
            --region us-west1 \
            --allow-unauthenticated
